inherit_from: .rubocop_todo.yml
require: rubocop-performance

AllCops:
  NewCops: enable

Style/RaiseArgs:
  EnforcedStyle: compact

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
